apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flask-hello-world
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/PaulMoroz/k8s.git
  ref:
    branch: main
