apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world-service
spec:
  type: NodePort
  selector:
    app: flask-hello-world
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30000
